{{- if or (not (empty (include "vcluster.plugin.clusterRoleExtraRules" . ))) .Values.rbac.clusterRole.create .Values.sync.nodes.enabled .Values.sync.persistentvolumes.enabled .Values.sync.storageclasses.enabled .Values.sync.priorityclasses.enabled .Values.sync.volumesnapshots.enabled -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "vcluster.clusterRoleName" . }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  {{- if or .Values.sync.nodes.enabled .Values.rbac.clusterRole.create }}
  - apiGroups: [""]
    resources: ["nodes", "nodes/status"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods", "nodes/proxy", "nodes/metrics", "nodes/stats"]
    verbs: ["get", "watch", "list"]
  {{- end }}
  {{- if or (and .Values.sync.nodes.enabled .Values.sync.nodes.syncNodeChanges) .Values.rbac.clusterRole.create }}
  - apiGroups: [""]
    resources: ["nodes", "nodes/status"]
    verbs: ["update", "patch"]
  {{- end }}
  {{- if or .Values.sync.persistentvolumes.enabled .Values.rbac.clusterRole.create }}
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "patch", "update", "get", "watch", "list"]
  {{- end }}
  {{- if or .Values.sync.storageclasses.enabled .Values.rbac.clusterRole.create }}
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "watch", "list"]
  {{- end }}
  {{- if or .Values.sync.priorityclasses.enabled .Values.rbac.clusterRole.create }}
  - apiGroups: ["scheduling.k8s.io"]
    resources: ["priorityclasses"]
    verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
  {{- end }}
  {{- if or .Values.sync.volumesnapshots.enabled .Values.rbac.clusterRole.create }}
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
  {{- end }}
  {{- include "vcluster.plugin.clusterRoleExtraRules" . | indent 2 }}
{{- end }}