{{- if (include "vcluster.createClusterRole" . ) -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "vcluster.clusterRoleName" . }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.globalAnnotations }}
  annotations:
{{ toYaml .Values.globalAnnotations | indent 4 }}
  {{- end }}
rules:
{{- if .Values.pro }}
  - apiGroups: ["cluster.loft.sh", "storage.loft.sh"]
    resources: ["features", "virtualclusters"]
    verbs: ["get", "list", "watch"]
{{- end }}
  {{- if or .Values.sync.nodes.enabled .Values.rbac.clusterRole.create }}
  - apiGroups: [""]
    resources: ["nodes", "nodes/status"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: [ "pods", "nodes/metrics", "nodes/stats"]
    verbs: ["get", "watch", "list"]
  {{- end }}
  {{- if and (or .Values.sync.nodes.enabled .Values.rbac.clusterRole.create) (or (not .Values.isolation.enabled) (and .Values.isolation.nodeProxyPermission.enabled .Values.isolation.enabled)) }}
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get", "watch", "list"]
  {{- end }}
  {{- if or (and .Values.sync.nodes.enabled .Values.sync.nodes.syncNodeChanges) .Values.rbac.clusterRole.create }}
  - apiGroups: [""]
    resources: ["nodes", "nodes/status"]
    verbs: ["update", "patch"]
  {{- end }}
  {{- if or .Values.sync.persistentvolumes.enabled .Values.rbac.clusterRole.create }}
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "patch", "update", "get", "watch", "list"]
  {{- end }}
  {{- if .Values.sync.nodes.enableScheduler }}
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses","csinodes","csidrivers","csistoragecapacities"]
    verbs: ["get", "watch", "list"]
  {{- end }}
  {{- if (include "vcluster.syncIngressclassesEnabled" . ) }}
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "watch", "list"]
  {{- end }}
  {{- if or .Values.sync.storageclasses.enabled .Values.rbac.clusterRole.create }}
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["create", "delete", "patch", "update", "get", "watch", "list"]
  {{- end }}
  {{- if or .Values.sync.hoststorageclasses.enabled (index ((index .Values.sync "legacy-storageclasses") | default (dict "enabled" false)) "enabled") .Values.rbac.clusterRole.create }}
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "watch", "list"]
  {{- end }}
  {{- if or .Values.sync.priorityclasses.enabled .Values.rbac.clusterRole.create }}
  - apiGroups: ["scheduling.k8s.io"]
    resources: ["priorityclasses"]
    verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
  {{- end }}
  {{- if or .Values.sync.volumesnapshots.enabled .Values.rbac.clusterRole.create }}
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
  {{- end }}
  {{- include "vcluster.plugin.clusterRoleExtraRules" . | indent 2 }}
  {{- include "vcluster.generic.clusterRoleExtraRules" . | indent 2 }}
  {{- if (not (empty (include "vcluster.serviceMapping.fromHost" . ))) }}
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]
  {{- end }}
  {{- if .Values.multiNamespaceMode.enabled }}
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "delete", "patch", "update", "get", "watch", "list"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
  {{- end }}
  {{- if .Values.proxy.metricsServer.nodes.enabled }}
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list"]
  {{- end }}
{{- end }}
