apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.globalAnnotations }}
  annotations:
{{ toYaml .Values.globalAnnotations | indent 4 }}
  {{- end }}
spec:
  type: {{ if eq .Values.service.type "LoadBalancer" -}}ClusterIP{{- else }} {{- .Values.service.type }}  {{- end }}
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
    - name: kubelet
      port: 10250
      targetPort: 8443
      protocol: TCP
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- range $f := .Values.service.externalIPs }}
    - {{ $f }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.service.type "NodePort" }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  selector:
    app: vcluster
    release: {{ .Release.Name }}
---
{{ if eq .Values.service.type "LoadBalancer" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.globalAnnotations }}
  annotations:
{{ toYaml .Values.globalAnnotations | indent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  selector:
    app: vcluster
    release: {{ .Release.Name }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $f := .Values.service.loadBalancerSourceRanges }}
    - "{{ $f }}"
    {{- end }}
  {{- end }}
{{- end }}
