{{- if .Values.init.manifests }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-manifests
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.globalAnnotations }}
  annotations:
{{ toYaml .Values.globalAnnotations | indent 4 }}
  {{- end }}
data:
  manifests: |-
    {{ .Values.init.manifests | nindent 4 | trim }}
    {{ tpl .Values.init.manifestsTemplate $ | nindent 4 | trim }}
  {{- if .Values.init.helm }}
  charts: |-
  {{- range .Values.init.helm }}
  {{- /* only render this chart entry if either of chart or bundle is defined */}}
  {{- if .chart }}
    - name: {{ .chart.name }}
      repo: {{ .chart.repo }}
      version: {{ .chart.version }}
      {{- if .chart.username }}
      username: {{ .chart.username }}
      {{- end }}
      {{- if .chart.password }}
      password: {{ .chart.password }}
      {{- end }}
      {{- if .insecure }}
      insecure: true
      {{- end}}
  {{- end }}
  {{- if .bundle }}
      bundle: {{ .bundle }}
  {{- end }}
  {{- if or .chart .bundle }}
      {{- if or .values .valuesTemplate }}
      values: |-
        {{ (.values | default "") | nindent 8 | trim }}
        {{ tpl (.valuesTemplate | default "") $ | nindent 8 | trim }}
      {{- end}}
      {{- if .release }}
      timeout: {{ .timeout | default "120s" | quote }}
      releaseName: {{ .release.name }}
      releaseNamespace: {{ .release.namespace }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
