name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/docs.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/docs.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
  OUT_DIR: build/
  TARGET_OUT_DIR: build/docs/v0.19

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"
      - name: Build Docs
        run: |
          yarn
          node ./node_modules/mdx-link-checker/index.js pages
          yarn build
        working-directory: ./docs
      - name: Prepare Deployment
        run: |
          if [ ! -z "$NETLIFY_ACCESS_TOKEN" ]
          then
            rm -rf $OUT_DIR/docs/fragments $OUT_DIR/docs/**/fragments
            mkdir -p tmp-$TARGET_OUT_DIR
            mv $OUT_DIR/* tmp-$TARGET_OUT_DIR
            mkdir -p $TARGET_OUT_DIR
            mv tmp-$TARGET_OUT_DIR/* $TARGET_OUT_DIR

            npm install -g netlify-cli@3.20.1
          fi
        working-directory: ./docs
      - name: Deploy Preview Site
        if: github.ref != 'refs/heads/main'
        run: |
          if [ ! -z "$NETLIFY_ACCESS_TOKEN" ]
          then
            netlify deploy --auth=$NETLIFY_ACCESS_TOKEN --site=$NETLIFY_SITE_ID --dir=$OUT_DIR
          fi
        working-directory: ./docs
      - name: Deploy Production Site
        if: github.ref == 'refs/heads/main'
        run: |
          if [ ! -z "$NETLIFY_ACCESS_TOKEN" ]
          then
            netlify deploy --auth=$NETLIFY_ACCESS_TOKEN --site=$NETLIFY_SITE_ID --dir=$OUT_DIR --prod
          fi
        working-directory: ./docs
