name: Unit tests

on:
  release:
    types: [created]
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "!test/**" # exclude changes in e2e tests
      - ".github/workflows/unit-tests.yaml"
      - "hack/test.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Execute all tests
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Execute unit tests
        run: ./hack/test.sh
